apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-nginx-blue
spec:
  replicas: 3
  selector:
      matchLabels:
        app: k8-nginx-app
  template:
    metadata:
      labels:
        app: k8-nginx-app
    spec:
      containers: 
        - name: k8-nginx-app
          image: ahdevops.azurecr.io/k8-blue-nginx:test-blue
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi