apiVersion: v1
kind: Service
metadata: 
  name: k8-nginx-app
  labels: 
    app: k8-nginx-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: k8-nginx-app
  type: LoadBalancer